services:
  influxdb:
    image: influxdb:2.7.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=org
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
      - 2003:2003
  chronograf:
    image: chronograf:1.9.4
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password

  grafana:
    image: grafana/grafana:9.5.12-ubuntu
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 3000:3000
    links:
      - influxdb
    volumes:
      - ./grafana_provisioning/:/etc/grafana/provisioning
